<a href="https://colab.research.google.com/github/Madhav2702/AI_ML_AVANTHI_MADHAV/blob/main/NUMPY_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np

In [13]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:

a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
# Get number of elements
a.size

3

In [8]:
# Get Type
a.dtype

dtype('int64')

In [10]:
# Gat size
a = np.array([1,2,3], dtype='int16')
a.itemsize

2

In [15]:
# print the abive matrix using numpy
a = np.ones((5,5))

inside = np.zeros((3,3))
inside[1,1] = 9
a[1:4,-4:-1] = inside
print(a)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
a = np.zeros((10))
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
a=np.random.randint(10,49,size=(10))
print(a)

[14 16 26 31 41 24 40 23 19 38]


In [22]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
a=np.arange(1,11)
print(a)
a[::-1]

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [48]:
x=np.arange(0,9)
b=x.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a=np.random.randint(0,8,size=(3,3))
print(a)
a[3:3]

[[5 4 7]
 [3 5 1]
 [5 2 4]]


array([], shape=(0, 3), dtype=int64)

In [58]:
a = np.random.randint(1,100, size = (10,10))


array([[12, 76, 55, 18, 79, 20,  5, 44, 97, 41],
       [12, 79, 27, 49, 48, 71, 45, 96, 68, 97],
       [29, 43, 15, 19, 76, 64, 18, 83, 93, 70],
       [11, 99, 28, 43,  4, 49, 52, 57, 53, 55],
       [46, 89, 98,  3, 51,  6, 31, 73, 94,  4],
       [72, 81, 85,  1, 95, 15,  7, 90, 42, 57],
       [99, 63, 30, 18, 77, 94, 75, 74, 81, 39],
       [32, 58, 29, 31, 75, 82, 79, 89, 16, 89],
       [77, 68, 43, 97, 61, 63,  3, 69,  5, 90],
       [33, 91, 16, 34, 48, 93, 90, 90, 35, 92]])

In [4]:
a = np.random.randint(1,100, size = (10,10))
print("Max = ", np.max(a))
print("Min = ", np.min(a))

Max =  99
Min =  1


In [5]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [6]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [7]:
x=np.random.rand(5,3)
print(x)
y=np.random.rand(3,2)
print(y)
np.matmul(x,y)

[[0.46427522 0.87776903 0.15497809]
 [0.7679974  0.73438209 0.24986799]
 [0.34114001 0.14030203 0.72269372]
 [0.07453099 0.74110944 0.38904894]
 [0.71169065 0.31665926 0.47020377]]
[[0.68028947 0.0138742 ]
 [0.24018891 0.84886331]
 [0.86911097 0.28361632]]


array([[0.66136509, 0.79550169],
       [0.91601398, 0.704912  ],
       [0.89387398, 0.32879802],
       [0.56683562, 0.7404753 ],
       [0.96887295, 0.41203202]])

In [8]:
x = np.array([0, 1, 2, 3, 4])
y=np.array([1, 3, 4])
print(np.intersect1d(x,y))

[1 3 4]


In [9]:
x=np.random.rand(10)
print(x)
x.sort()
print(x)


[0.04511758 0.78769102 0.40620878 0.13140229 0.37038257 0.6664217
 0.05567344 0.89834939 0.03663456 0.18258474]
[0.03663456 0.04511758 0.05567344 0.13140229 0.18258474 0.37038257
 0.40620878 0.6664217  0.78769102 0.89834939]
