<a href="https://colab.research.google.com/github/Madhav2702/AI_ML_AVANTHI_MADHAV/blob/main/WEEK_1_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Q1. Given two NumPy arrays arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]), perform element-wise addition



In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr2=np.add(arr1,arr2)
arr2

array([5, 7, 9])

2.Access and print the element at the second row and third column of a given 2D NumPy array arr.

Take the array to be: [[1,2,3,4,5], [4,2,7,8,5], [6,2,9,1,0]]

In [ ]:
arr=np.array([[1,2,3,4,5],[4,2,7,8,9],[6,2,9,1,0]])
element=arr[1,2]
element

7

3.Reshape a given 1D array arr of size 10 into a 2D array of shape (5, 2). In [ ]:

Take the array as: [1,2,3,4,5,6,7,8,9,10]

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Q4. Extract the first three elements from a given NumPy array arr.

In [ ]:
x=np.array([1,2,3,4, 5, 6, 7, 8])
x[0:3:1]

array([1, 2, 3])

5.Define 2 arrays arr1 and arr2 and compute the dot product

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.dot(arr1,arr2)

70

6.Compute the mean, median, and standard deviation of a given NumPy array arr.

In [ ]:
arr=np.array([3,6,9,12,15])
x=np.mean(arr)
y=np.median(arr)
z=np.std(arr)
print(x)
print(y)
print(z)

9.0
9.0
4.242640687119285


7.Stack two given NumPy arrays arr1 and arr2 horizontally.

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

8.Perform matrix multiplication on two given NumPy arrays arr1 of shape (3, 2) and arr2 of shape (2, 3).

In [ ]:
arr1=np.full((3,2),2)
print(arr1)
arr2=np.full((2,3),3)
print(arr2)
np.matmul(arr1,arr2)

[[2 2]
 [2 2]
 [2 2]]
[[3 3 3]
 [3 3 3]]


array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

9.Given a NumPy array arr, create a new array containing only the elements greater than 10.

In [ ]:
arr=np.array([[5,15,17,9],[20,4,25,13]])
print(arr)
arr1=arr[arr > 10]
arr1

[[ 5 15 17  9]
 [20  4 25 13]]


array([15, 17, 20, 25, 13])

10.Sort the elements of a given NumPy array arr in descending order.

In [ ]:
arr=np.array([15,7,24,3,12,6])
print(arr)
arr[::-1].sort()
arr

[15  7 24  3 12  6]


array([24, 15, 12,  7,  6,  3])

**PANDAS**

In [ ]:
import pandas as pd
data = {
    'Name': ['John', 'Alice', 'Bob', 'Emily', 'David'],
    'Age': [25, 30, 35, 28, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Seattle'],
    'Salary': [50000, 60000, 70000, 55000, 80000]
}

df = pd.DataFrame(data)
df

Name  Age           City  Salary
0   John   25       New York   50000
1  Alice   30    Los Angeles   60000
2    Bob   35        Chicago   70000
3  Emily   28  San Francisco   55000
4  David   40        Seattle   80000

Q1. Display the first 5 rows of the DataFrame.

In [ ]:
df.head(5)

Name  Age           City  Salary
0   John   25       New York   50000
1  Alice   30    Los Angeles   60000
2    Bob   35        Chicago   70000
3  Emily   28  San Francisco   55000
4  David   40        Seattle   80000

Q2. Access and print the 'Age' column of the DataFrame.

In [15]:
df['Age']

0    25
1    30
2    35
3    28
4    40
Name: Age, dtype: int64

Q3. Sort the DataFrame based on the 'Salary' column in ascending order.

In [16]:
df.sort_values('Salary', ascending=True)

Name  Age           City  Salary
0   John   25       New York   50000
3  Emily   28  San Francisco   55000
1  Alice   30    Los Angeles   60000
2    Bob   35        Chicago   70000
4  David   40        Seattle   80000

Q4. Calculate and display basic statistics (mean, median, min, max) for the 'Salary' column.

In [17]:
x=df['Salary'].mean()
print(x)
y=df['Salary'].median()
print(y)
min=df['Salary'].min()
print(min)
max=df['Salary'].max()
max

63000.0
60000.0
50000


80000

Q5. Filter the DataFrame to show only the rows where the 'Age' is greater than 30.



In [18]:
df.loc[df['Age']>30]


Name  Age     City  Salary
2    Bob   35  Chicago   70000
4  David   40  Seattle   80000

Q8. Update the 'Salary' of the person named 'Bob' to 72000.



In [19]:
df.loc[df['Name']=='Bob','Salary']=72000
df


Name  Age           City  Salary
0   John   25       New York   50000
1  Alice   30    Los Angeles   60000
2    Bob   35        Chicago   72000
3  Emily   28  San Francisco   55000
4  David   40        Seattle   80000

Q6. Add a new column 'Gender' to the DataFrame with values 'Male' for the first three rows and 'Female' for the last two rows.

In [22]:
df=pd.DataFrame(data)
df['Gender']=['Male','Male','Male','Female','Female']
df

Name  Age           City  Salary  Gender
0   John   25       New York   50000    Male
1  Alice   30    Los Angeles   60000    Male
2    Bob   35        Chicago   70000    Male
3  Emily   28  San Francisco   55000  Female
4  David   40        Seattle   80000  Female

Q7. Group the DataFrame by 'City' and calculate the average salary in each city.



In [21]:
df=pd.DataFrame(data)
average=df.groupby('City')['Salary'].mean()
print(average)

City
Chicago          70000.0
Los Angeles      60000.0
New York         50000.0
San Francisco    55000.0
Seattle          80000.0
Name: Salary, dtype: float64


Q10. Rename the 'Name' column of the DataFrame to 'Full Name' and display the updated DataFrame.



In [26]:
df=pd.DataFrame(data)
x=df.rename(columns={'Name':'Full Name'})
x

Full Name  Age           City  Salary
0      John   25       New York   50000
1     Alice   30    Los Angeles   60000
2       Bob   35        Chicago   70000
3     Emily   28  San Francisco   55000
4     David   40        Seattle   80000